(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> need more than 1 value to unpack"
p3
sS'layer'
p4
S'/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py'
p5
sS'code'
p6
S'<code object <module> at 0x1045db7b0, file "/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py", line 268, in <module>\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py", line 261, in payment_history\n    for r in db(db.payment_history.landlord == auth.user.id).select():\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/objects.py", line 2250, in select\n    return adapter.select(self.query, fields, attributes)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/adapters/sqlite.py", line 82, in select\n    return super(SQLite, self).select(query, fields, attributes)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/adapters/base.py", line 762, in select\n    return self._select_aux(sql, fields, attributes, colnames)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/adapters/base.py", line 741, in _select_aux\n    return processor(rows, fields, colnames, cacheable=cacheable)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/adapters/base.py", line 305, in parse\n    for row in rows\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/adapters/base.py", line 231, in _parse\n    value = self.parse_value(value, fit, ft, blob_decode)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/adapters/base.py", line 198, in parse_value\n    return self.parser.parse(value, field_itype, field_type)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/parsers/__init__.py", line 101, in parse\n    return self.registered[field_itype](value, field_type)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/parsers/__init__.py", line 76, in __call__\n    return self.call(value, field_type)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/parsers/__init__.py", line 73, in _call\n    return self.f(self.parser, value)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/parsers/sqlite.py", line 32, in _datetime\n    self, value)\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/packages/dal/pydal/parsers/base.py", line 102, in _datetime\n    (y, m, d) = map(int, date_part.split(\'-\'))\nValueError: need more than 1 value to unpack\n'
p11
s.